# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-methylseq-1.2
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # bismark
  - conda-forge::openjdk=8.0.144 # Needed for FastQC - conda build hangs without this
  - fastqc=0.11.8
  - trim-galore=0.5.0
  - samtools=1.9
  - bowtie2=2.3.4.3
  - bismark=0.20.0
  - qualimap=2.2.2b
  - multiqc=1.7
  # bwa-meth aligner
  - picard=2.18.21
  - bwameth=0.2.2
  - methyldackel=0.3.0
