# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-methylseq-1.4
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::fastqc=0.11.8
  - conda-forge::r-markdown=1.1
  # Default bismark pipeline
  - bioconda::trim-galore=0.6.4
  - bioconda::samtools=1.9
  - bioconda::bowtie2=2.3.5
  - bioconda::hisat2=2.1.0
  - bioconda::bismark=0.22.2
  - bioconda::qualimap=2.2.2c
  - bioconda::preseq=2.0.3
  - bioconda::multiqc=1.7
  # bwa-meth pipeline
  - bioconda::picard=2.21.3
  - bioconda::bwameth=0.2.2
  - bioconda::methyldackel=0.4.0
