# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-methylseq-1.5
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # nf-core dependencies
  - conda-forge::python=3.7.3
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.6.1
  - conda-forge::pigz=2.3.4
  - bioconda::fastqc=0.11.9
  # Default bismark pipeline
  - bioconda::trim-galore=0.6.5
  - bioconda::samtools=1.10
  - bioconda::bowtie2=2.3.5
  - bioconda::hisat2=2.2.0
  - bioconda::bismark=0.23.0
  - bioconda::qualimap=2.2.2d
  - bioconda::preseq=2.0.3
  - bioconda::multiqc=1.9
  # bwa-meth pipeline
  - bioconda::picard=2.22.2
  - bioconda::bwameth=0.2.2
  - bioconda::methyldackel=0.5.1
# added
  - bioconda::samblaster=0.1.24
  - bioconda::bedtools=2.29.1
  - bioconda::biscuit=0.3.16.20200420=h2b0c03c_3
  - bioconda::bcftools=1.10
  - conda-forge::parallel
  - gawk=5.1.0
